from .engineering import (
    GeometryConflict,
    dimension_conflicts,
    geometry_summary,
    pressure_relationships,
    sync_room_geometry_to_analysis,
)
from .geometry import (
    Camera3D,
    Viewport2D,
    floor_bounds,
    hit_test_object,
    hit_test_room,
    nearest_room_wall,
    object_prism,
    point_in_polygon,
    room_prism,
    room_resize,
    snap_point,
    snap_value,
)
from .model import (
    LAYOUT_SCHEMA,
    LAYOUT_SCHEMA_VERSION,
    OBJECT_KINDS,
    Floor,
    GridConfig,
    LayoutFormatError,
    LayoutObject,
    Room,
    SpatialLayout,
    new_id,
)
from .validation import ValidationIssue, layout_is_valid, rooms_overlap, validate_layout

__all__ = [
    "Camera3D",
    "Floor",
    "GeometryConflict",
    "GridConfig",
    "LAYOUT_SCHEMA",
    "LAYOUT_SCHEMA_VERSION",
    "LayoutFormatError",
    "LayoutObject",
    "OBJECT_KINDS",
    "Room",
    "SpatialLayout",
    "ValidationIssue",
    "Viewport2D",
    "dimension_conflicts",
    "floor_bounds",
    "geometry_summary",
    "hit_test_object",
    "hit_test_room",
    "layout_is_valid",
    "nearest_room_wall",
    "new_id",
    "object_prism",
    "point_in_polygon",
    "pressure_relationships",
    "room_prism",
    "room_resize",
    "rooms_overlap",
    "snap_point",
    "snap_value",
    "sync_room_geometry_to_analysis",
    "validate_layout",
]
